### PR TITLE
show preloader only while loading

### PR DESCRIPTION
**Pull request by cell303**

### CODE REVIEW

**Comment by emri99** [comment]
Is there a reason for this pull request not to be merged ? I want it too ;)

**Comment by idolizesc** [comment]
@lettertwo Any word on merging this? Thanks!

**Comment by lettertwo** [comment]
@cell303 apologies for the long delay getting this in. v1.2.0 is on npm now.

@emri99 @idolizesc thanks for pinging!

**Comment by emri99** [comment]
Thanks You ;)

**Pull request merged**
