### PR TITLE
Allow for `style` property

### PR DESCRIPTION
**Pull request by ta2edchimp**
This is just a small extension of the ImageLoader component to allow specifying a `style` property to be applied as a style attribute to the rendered DOM node.

### CODE REVIEW

**Comment by lettertwo** [comment]
Thanks for this PR! I'd like to just pull this in, but I'm afraid it would have to change in fairly short order, as we're currently looking at a general solution for delivering props to the underlying `` in #18. So, a merger between the solution we're discussing there and your solution might look something like:

```jsx

// `imgProps` are passed as props to the underlying `<img>` DOM node
<ImageLoader imgProps={{style: {border: 'none'}}} />

```
Would that work for you?

**Comment by ta2edchimp** [comment]
Hi, thanks for the feedback.

I like the proposal from #18, but I don't think that an added `imgProps` property would interfere with my proposal for an `style` property, because `imgProps` will be applied to the contained `img` element (when — this is, if — successfully loaded and rendered), whereas the `style` would be applied to the container component (the `wrapper`), regardless of the success or even progress of the contained image.

In the end, I personally would like to see both of them eventually. What do you think?

**Comment by lettertwo** [comment]
Aha, yes, you're right, i misunderstood your intention! I"m still inclined to pull this in, but i'd like to pull in just the change, and reserve the [version bump] and [changelog updates] for when we are ready to cut the next release (which will be soon). If you've got the time, would you mind updating the PR to include just the change and the documentation (a simple [test] would be icing on the cake, but again, if you have the time)? If not, no worries, i can work with you've already got here.

Longer-term, we're considering simply forwarding any props given to `ImageLoader` (that aren't specific to it) to the wrapper element, and then adding something like the `imgProps` feature discussed in #18 to allow customization of the underlying `` itself.

[version bump]: https://github.com/ta2edchimp/react-imageloader/commit/23a40b1694b55e42c2fc901db6f4021c6f72df15

[changelog updates]: https://github.com/ta2edchimp/react-imageloader/commit/6df1f8387707aeb30b5be4e29fd465c0f5311af6#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR1

[test]: https://github.com/hzdg/react-imageloader/blob/6dba5b4c4824ca852e579b5cedc19376b557c858/test/tests.js#L13-L18

**Comment by ta2edchimp** [comment]
I modified the PR accordingly. Let me know if the test is sufficient.

**Comment by lettertwo** [comment]
Looks great, thanks a lot for the test!

**Pull request merged**
